#!/usr/bin/env bash
# a Bash script that will display information about subdomains.
# shellcheck disable=SC2086


DOMAIN=$1
SUBDOMAIN=$2
RECORDTYPE=''
DESTINATION=''

subdomainInfo () {
	if [[ -z "$SUBDOMAIN" ]]; then
		RESULTLINE=$(dig "$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
		RECORDTYPE=$(echo "$RESULTLINE" | awk '{print $4}')
		DESTINATION=$(echo "$RESULTLINE" | awk '{print $5}')
	else
		RESULTLINE=$(dig "$SUBDOMAIN.$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
		RECORDTYPE=$(echo "$RESULTLINE" | awk '{print $4}')
		DESTINATION=$(echo "$RESULTLINE" | awk '{print $5}')
	fi
}

if [[ -n "$SUBDOMAIN" ]]; then
	subdomainInfo "$DOMAIN" "$SUBDOMAIN"
	echo "The subdomain $SUBDOMAIN is a $RECORDTYPE record and points to $DESTINATION"
else 
	for SUBDOMAIN in www lb-01 web-01 web-02; do
		subdomainInfo "$DOMAIN" "$SUBDOMAIN"
		echo "The subdomain $SUBDOMAIN is a $RECORDTYPE record and points to $DESTINATION"
	done
fi
