#!/usr/bin/env bash
# a Bash script that will display information about subdomains.
# shellcheck disable=SC2086

subdomainInfo () {
	RESULTLINE=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
	RECORDTYPE=$(echo "$RESULTLINE" | awk '{print $4}')
	DESTINATION=$(echo "$RESULTLINE" | awk '{print $5}')
	echo "The subdomain $2 is a $RECORDTYPE record and points to $DESTINATION"
}
if [[ -n "$2" ]]; then # if subdomain exist
	subdomainInfo "$1" "$2"
else 
	for SUBDOMAIN in www lb-01 web-01 web-02; do
		subdomainInfo "$1" "$SUBDOMAIN"
	done
fi
