#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server


if [[ "$#" < 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 0
fi

SOURCE="$1"
TARGET="$3@$2:~/"

if [[ "$4" ]]; then
	IDENTITY="$4"
	scp -i "$IDENTITY" -o "StrictHostKeyChecking no" "$SOURCE" "$TARGET"
else
	scp -o "StrictHostKeyChecking no" "$SOURCE" "$TARGET"
fi
