#!/usr/bin/env bash
# a script that installs and configures nginx server to return Hello World!, and redirect /redirect_me to youtube

#sudo dpkg -l nginx > /dev/null 2>&1 # check if nginx is installed already
#if [[ "$?" == 1 ]]; then # if not installed, then install nginx
#	sudo apt-get update -y
#	sudo apt-get install -y nginx
#fi
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.google.com permanent;" /etc/nginx/sites-available/default
#echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null # create a file with the text Hello World!
#redirect="\trewrite ^/redirect_me http://www.google.com permanent;"
#sudo sed -i "/server_name;/ a\\$redirect" /etc/nginx/sites-available/default
sudo service nginx start # start the server if not already started
