#!/usr/bin/env bash
# a script that installs and configures nginx server to return Hello World!,
# and to redirect to another site, and to return a custom error page

sudo dpkg -l nginx > /dev/null 2>&1 # check if nginx is installed already
if [[ "$?" == 1 ]]; then # if not installed, then install nginx
	sudo apt-get update -y
	sudo apt-get install -y nginx
fi

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null # create a file with the text Hello World!

redirect="\trewrite ^/redirect_me http:/www.youtube.com permanent;\n"
custom_error="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom404.html {\n\t\troot /var/www/html;\t\tinternal;\n\t}"
sudo sed -i "/server_name;/a\\$redirect$custom_error" /etc/nginx/sites-available/default

sudo service nginx start # start the server if not already started
