#!/usr/bin/env bash
# a script that installs and configures a Haproxy load balancer


# update package repository
sudo apt-get -y update
sudo apt-get -y upgrade

# install haproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy

# configure haproxy
web1='54.174.230.152'
web2='54.160.103.251'
sed -i -e "$afrontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend nginx_webservers\n\n" /etc/haproxy/haproxy.cfg
sed -i -e "$abackend nginx_webservers\n\tbalance roundrobin\n\tserver websvr1\t$web1 check\n\tserver websvr2\t$web2 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
