#!/usr/bin/env bash
# a script that installs and configures a Haproxy load balancer

if ! haproxy -v &> /dev/null ; then
	# update package repository
	sudo apt-get -y update
	sudo apt-get -y upgrade

	# install haproxy
	sudo apt-get -y install --no-install-recommends software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
	sudo apt-get -y update
	sudo apt-get -y install haproxy=2.6.\*
	sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
elif sudo grep -wq "frontend" /etc/haproxy/haproxy.cfg; then

	# uninstall haproy
	sudo apt-get purge -y haproxy
	sudo apt -y autoremove

	# update package repository
	sudo apt-get -y update
	sudo apt-get -y upgrade

	# install haproxy
	sudo apt-get -y install --no-install-recommends software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
	sudo apt-get -y update
	sudo apt-get -y install haproxy=2.6.\*
	sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
elif [[ ! -f /etc/haproxy/haproxy.cfg.original_copy ]]; then
	sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
fi

# configure haproxy
web1='54.174.230.152'
web2='54.160.103.251'
echo -e "\nfrontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend nginx_webservers" | sudo tee --append /etc/haproxy/haproxy.cfg
echo -e "\nbackend nginx_webservers\n\tbalance roundrobin\n\tserver websvr1 $web1:80 check\n\tserver websvr2 $web2:80 check" | sudo tee --append  /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
