#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.
# Requirements:

# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

for i in $(seq 100);do
	if [[ $(("$i" % 3)) == 0 ]];then
		echo -n "Fizz"
	fi
	if [[ $(("$i" % 5 )) -eq 0 ]];then
		echo -n "Buzz"
	fi
	if [[ $(("$i" % 3 )) != 0 && $(("$i" % 5 )) != 0 ]];then
		echo -n "$i"
	fi
	echo ""
done
