#!/usr/bin/env bash
# a Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

awk -F '["]' '{print $1,$3}' apache-access.log | awk -F '\\[|]' '{print $1,$3}' | awk '{print $1,$4}'
#"=",$1,"=",$2,"=",$3,"=",$4,"=",$5,"="}'
