#!/usr/bin/env bash
# Based on your previous task, write a Bash script that groups visitors by IP and HTTP status code, and displays this data.

awk '{print $1,$9}' apache-access.log | sort -n | uniq -c | sort -rn 
