#!/usr/bin/env bash
# a Bash script that displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
for line in *;do
	echo "$line" | grep -o "[-].*$" | sed "s/-//"
	echo "$line" | grep -v -
done
