#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.

echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" > ~/hosts.tmp
grep -vE 'localhost|facebook' /etc/hosts >> ~/hosts.tmp
cp ~/hosts.tmp /etc/hosts
