#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs on the machine it’s executed on.

ifconfig | sed -e 's/^[\t ]*//' | grep 'inet ' | cut -f 2 -d " "
# ifconfig | awk '/inet / {print $2}'
