#!/usr/bin/env bash
# script to configure nginx to run with non-root

# chown -R nginx:nginx /var/log/nginx
# chown -R nginx:nginx /etc/ngix
# chown -R nginx:nginx /usr/share/nginx
# chown -R nginx:nginx /run/nginx.pid
chmod 644 /etc/nginx/nginx.conf
sed -i "/#user www-data;/a \\user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start 
