#!/usr/bin/env bash
# script to configure nginx to run with non-root

chmod 644 /etc/nginx/nginx.conf
sed -i "/#user www-data;/a \\user nginx;" /etc/nginx/nginx.conf
sed -i "/listen 80 default_server;/ s/80/8080/" /etc/nginx/sites-available/default
sed -i "/listen \[::\]:80 default_server ipv6only=on;/ s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start 
